version: "3"

services:

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - data:/usr/share/nginx/html

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/app
